<?php

	//application details
		$apps[$x]['name'] = "Aastra";
		$apps[$x]['uuid'] = "c3b13bbc-3015-4c09-87e8-416749b29f66";
		$apps[$x]['category'] = "Vendor";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "";
		$apps[$x]['description']['en-gb'] = "";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";
	//default aastra settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "09a02a56-b091-45d9-9a39-f07786284d47";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "gmt_offset";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Aastra timezone offset in minutes (e.g. 300 = GMT-5 = Eastern Standard Time)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "dc2fd4ed-fb70-4c95-a8d7-f63410034e14";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "time_format";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Aastra clock format";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "49135ee7-3f8a-4223-85be-985ffb2dc54e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "date_format";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Aastra date format";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ec5db84d-8a58-4ea3-aa46-1a612dfd5522";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "ptime";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "20";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set Aastra ptime";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d77aada5-d31b-4624-9b38-172618974afd";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "silence_suppression";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable Aastra codec silence suppression (on / off)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e1e166ad-4bb9-47f8-a7ba-746f994df178";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "zone_minutes";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Offset in minutes from GMT, 300 = GMT-5 = Eastern Standard Time, -120 = GMT+2 = Eastern European Time";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "20e31da9-90e7-4a3d-945c-f4046c50c1ff";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "aastra";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "sip_silence_suppression";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Aastra SIP silence suppression - silence suppression: deactivated (0), activated (1); enabled on G.711 with CN(RFC3389) or G.729AB";
